### ISSUE TITLE
Support Compressed Game File Type

### ISSUE THREAD

**Issue by trymeouteh** [espes/xqemu#105]
This reddit post shows people how to compress there games files with other consoles.

https://www.reddit.com/r/emulation/comments/3g933n/guide_reduce_the_size_of_your_ps2_gc_wii_x360_ds/

I think it would be handy if XQEMU considered doing something like this. Since Xbox Games are kinda large in size. Making them smaller in size and be able to run them it would be useful especially if a user has a lot of Xbox Games.

A good option in my opinion is to do what PCSX2 did which was allow gzip files to be opened as games.

**Comment by JayFoxRox** [comment]
I'm **strongly** against this.

XQEMU does LLE. We want accurate disc images (which are always ~8GiB). If your image is not accurate, it will fail copy protection checks (which are emulated as part of the original kernel).
[I've also looked into compressing accurate XISO dumps](https://www.reddit.com/r/crypto/comments/7d77yq/need_help_state_key_recovery_or_bruteforce_on/dpx896v/). However, I don't think this is what you are asking for (it would also not be a part of XQEMU).

However, if-need-be XQEMU will load any XISO image. So if you want, you can already use ripped/stripped XISOs which are about the size of the game.

Compressing with gzip or other methods doesn't really help either because games consist mostly of already compressed audio, movies and textures.

If you *still* want to this this, there are virtual filesystems like fuse which can do the extraction. Some host filesystems also allow compression (although not as efficiently).
Another option to convert your images to one of the various qemu image formats. qcow supports compression for example. I'm not sure wether qcow would be able to handle all disc metadata XQEMU will eventually require, but aside from that: it should be working already.

**Comment by trymeouteh** [comment]
Every other emulator allows some kind of compressed file. I am not talking about trimming files. Even Project 64 allows you to place a n64 rom file into a zip folder which could reduce the size of the game by up to 40%. Not all games will be reduced in big numbers but the smaller we can make game files the better.

And it will take more to run a compressed game since the emulator will need to decompress it to read the game but in the long run when computers get faster it will be a great feature. For emulators like PCSX2 and Dolphin compress game files don't take any longer to load than a normal ISO file with modern computers.

And I understand that adding some new file type or creating a new file type that will act as a compressed Xbox game would be hard but you can just do what some emulators do and support a compressed file type like GZIP, ZIP or 7Z which users can easily compress their ISO/XISO files into and add support for the emulator to read these file types.

**Comment by espes** [comment]
will think about it after XQEMU works
