### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by SilverSzymonPL** [espes/xqemu#68]
I'm running windows. after downloading MSYS2 i copypasted the commands needed but none of them worked. and yes, i cloned xqemu.

**Comment by JayFoxRox** [comment]
I'm tempted to close this (but I'll let @espes decide what to do).
It's not an issue with the code, so it probably shouldn't be here.

In case we are supposed to handle support here: provide more information please.
- What version of windows?
- Do you have MSYS setup properly?
- Do you have a toolchain in MSYS installed?
- Which revision did you clone?
- What did you run?
- What happened / output?
- Are you an experienced dev or just a user?
- ...

**Comment by SilverSzymonPL** [comment]
Well, every single compile command ends with an error: "(The first word of any command i input) is not a valid command."

**Comment by JayFoxRox** [comment]
You probably have enough bandwidth to show your full log in proper formatting, rather than this.
- We still don't know what you did, what you are trying to run etc..

You are probably not running a mingw shell or your MSYS installation is incomplete because you didn't follow the steps on their website correctly.

**Comment by SilverSzymonPL** [comment]
ah, whatevs. i'm just gonna wait untill some sort of a video guide pops up. this can be closed now.
