### ISSUE TITLE
Error when compiling for macOS Sierra

### ISSUE THREAD

**Issue by AmazingVanish** [espes/xqemu#70]
I am getting the following error when attempting to compile using the command given in the Getting Started section:

Undefined symbols for architecture x86_64:
  "_use_rt_clock", referenced from:
      _get_clock in block.o
      _get_clock in qemu-timer.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [qemu-nbd] Error 1

I have installed all of the libs I could find as prereqs for Qemu. Any ideas?

**Comment by JayFoxRox** [comment]
Can you compile the stock qemu [1.7.2]? Also, can you provide a full log / terminal session [including configure and make] ?

**Comment by AmazingVanish** [comment]
Build log attached.

[xqemu build log.txt](https://github.com/espes/xqemu/files/755723/xqemu.build.log.txt)

**Comment by intrepidsilence** [comment]
Was this ever solved?

**Comment by JayFoxRox** [comment]
I don't know.
We never got a stock qemu log to compare against. I'm guessing the problem is not related to xqemu itself. Looks like broken linker / bad linker to compiler compatibility or something - if anything, this seems to be a problem with our docs.

Closed due to inactivity. Please re-open if this is still an issue.

**Comment by JayFoxRox** [comment]
@AmazingVanish It was a bug in QEMU after all. fixed in 5cf8131

**Comment by AmazingVanish** [comment]
Sweet. Thanks!
