### ISSUE TITLE
Get rid of nv2a proxy struct

### ISSUE THREAD

**Issue by PatrickvL** [espes/xqemu#71]
The xqemu Wiki mentions in a TODO "get rid of nv2a proxy struct".

What does this entail?
Why is it desirable to get of this struct?
What's the alternative?
Why is that better?

**Comment by espes** [comment]
The TODO refers to cleaning up all the cases where we have members of NV2AState mirror hardware state where in hardware the state is kept in the exposed registers. This forces us to understand what the hardware is actually doing and describe the behaviour more accurately. For example, making sure we emulate the register state changes of pgraph methods is required for software context switching to be emulated correctly (though for the xbox that doesn't matter because Microsoft's driver only uses one context).

There use to be a lot more of this. The main remaining offender is all the FIFO context. I started to rewrite that in the fix-fifo branch.

**Comment by espes** [comment]
mostly done!
